### PR TITLE
BUG: Fix devroye sampler from returning -NAN for proposal sample in corner cases

### LINKED ISSUE #83: BUG: sampler occasionally hangs
hello @zoj613. thanks again for the great package. i'm sometimes seeing the sampler stall/hang.

this is the smallest reproducible script i've been able to come up with. hopefully this will surface the issue on your system as well...

```python
import numpy as np
from polyagamma import random_polyagamma

bad_state = {'bit_generator': 'PCG64', 'state': {'state': 286445528977372604878304246648472662937,
             'inc': 87136372517582989555478159403783844777}, 'has_uint32': 1, 'uinteger': 165759272}

rng = np.random.default_rng(0)
rng.__setstate__(bad_state) # if this line is commented out the sampler returns as usual

bad_z = np.array([-7.7159955279217645, -5.688383408336662, 2.4103941716465282, -4.90626055141453, -10.954245335948691, -5.773287517761037, -6.311513126139971, -7.695398984797436, -6.3832143833769655, -2.564762898556397, -2.3118010212900364, -4.718389207128771, 1.7601304947837049, -8.42732831735728, -3.862044943685949, -5.7787177292797605, -20.29932237601833, -3.6537410213424506, -8.461559085158452, -9.89944682307928, -5.696226884564253, -9.1250497748862, -7.5979075278743196, -10.757307721780466, -9.084993406805888, -7.685660133809492, -8.823505426373037, -1.165363252205105, -7.300061338287363, -6.427860810082782, -3.0221567231515736, -6.328243375567028, -1.6684474535428366, 1.2254003055223004, -6.758976991522837, -7.107719705832688, -6.981026096361312, -6.66207820518799, -6.463985934661833, -5.777396543276716, -5.18125065175635, -7.6786030941131, -7.010016457052919, -0.9000165011313692, -2.4956708005547337, -1.0192764466185116, -8.01812363871118, -3.5894788262246404, -7.522172263151698, -7.526912680584633, -2.1891046299307213, -10.424348071997604, -2.202330318247364, 2.577534253458892, -7.687467971494408, -9.688685210322241, -3.634411805182897, -1.1908965060811223, -8.582967381893358, -2.4486844411942603, -3.1510089973232405, -4.889688631223909, -8.71235438853951, 0.23921879992437667, -1.9378540362513546, -3.8802915418435457, -7.841221724612904, -0.2955492911347388, -1.3542976365653816, -6.8293614107612015, -9.210993532041117, -2.887974970403637, -7.048053453517596, -11.179085399642343, -3.201835581408629, -9.36825203899268, 1.217126729237389, -11.81015329865815, -2.8882319014328415, -3.385019075846617, -7.703097676843385, -4.220019528089502, -2.5664772197876733, -1.6384797314223714, -3.764091299623171, -3.1117359964962104, -5.210124763540389, -5.529963633124693, -12.473719197610416, -6.789538678553491, -9.939334768370019, -5.400019923735151, -11.81993965937595, -4.53756250687539, 0.5913833358729432, -0.5766533426839153, -5.843879901728336, -0.29539872879535967, -5.5296471395017255, -6.9739394740890575, -4.899325406529429, -8.190228267953618, -2.298693288379017, -12.56079570496085, -5.2361155118083476, -0.8546938483482389, -7.5999273795647815, -3.1322396929326826, -7.520184381515393, -4.382074746373018, -6.617253735425976, -13.66693607501863, -9.407616048212464, -2.4494309076866214, -2.6300391483943977, -10.863656921744937, -3.594100095197258, -0.7562807684032578, -3.0860453106408974, -8.678960150780716, -8.284999367859644, -11.270628516605488, -2.8037376000322034, -5.781402398643731, 2.697850623115234, -8.81352963529242, -0.37103120086357766, -5.722245592378262, -4.406450954903647, -9.880914623244749, -2.0592691145346746, -5.058151894855059, 0.9438105597141462, -2.013557031693369, -2.2185189585681138, -7.9966281089095, 3.489025571184194, -3.279924879114724, -1.186609088971064, -9.970855880293058, -6.667642513611053, -8.84694390533457, -3.978299814282288, -6.06052387224828, -3.0605332422625096, -5.049904760405894, -7.05815944833525, -2.2529170769032745, -10.89285943942715, -11.068038514304959, -2.3860733591154197, -0.08798811481825997, -9.316088255444871, -6.4668465057920965, -6.811544859596736, -4.05258596226946, -5.280669655258182, -7.365182715882279, -4.543439696164741, -5.148616554927539, -3.750774897823457, -12.193567338305948, -0.6957150084697634, 2.808564255056562, -0.6876715432885856, -8.02318701562676, -6.977896662944611, -9.524408581426663, -9.781958289842166, -4.271102793111396, -1.0411750040334482, -8.714375164603663, -5.21215745145907, -3.963140641101465, -2.093652102829111, -8.136657864869417, -3.7372133579288045, -4.544260411064354, -2.315289889567245, -10.575288150277192, -10.836499727310812, -2.2017240079309413, -4.319009311151649, -3.393951127373044, 2.3319051665861164, -6.415511447193612, -12.000559977123228, -3.932846640222944, -4.2839988799104525, 0.3748367571387474, -4.38119258087972, -4.9975878200024155, -1.215029777311032, -4.432040728644365, -4.055317480451655, -8.015277250238704, -7.791193041364883, -1.208604812146648, -7.464106652678793, -3.3089459574695512, 0.565354111599949, 4.006234308066209, -5.411213095562011, -5.333275728492514, -7.168529856598479, -4.888233382212302, -11.264199152466603, -6.165752583907858, -7.63420257164309, -3.0591368035023128, -4.1187622907820485, -15.213779959499778, -6.1490315083215155, -5.3856648070059325, -2.908478940128666, -11.145910344518146, -6.997522954584618, -7.299823673363338, -8.129460491657383, -0.9268450449842698, -4.477811838108732, -7.464161846723406, -6.660454515563282, 0.08286648798164276, -3.0350911859177643, -5.231581623118869, -4.0344359736463336, -3.007616728277827, -6.812590583179762, -4.751400902831156, -6.2289966072471685, -6.698795132832843, -6.046464323967813, -9.166306216389106, -6.749800617887599, 1.0684002553397738, 3.035042848011444, -8.956817926179387, -5.432044283421149, -2.828781674885361, -3.0467644287247553, 1.1394259540556186, 1.7625068559757242, -10.022373510387043, -6.256482949081717, -3.641392297856366, -6.971862587394393, -3.5125729470562996, -9.911990130316614, -0.37314856765888305, -6.679089485721889, -3.562972669877401, -1.6164110624843309, -6.353916245342262, -3.572645464566901, -8.919922783159063, -6.1019248023136585, -0.1555105784862203, -1.828608864388647, -4.177580353542247, -5.612723250588665, 1.2993931058958985, -9.570976847117686, -3.8136562734762087, -2.8270100999665284, -5.742013130680353, -9.883000701084573, -7.32928907338796, -2.944968201160664, -5.929924037218706, -3.7345046817224348, -4.22621858869544, -8.378613350426871, 0.7021251460062743, -4.100515471133535, -11.943186161950807, -8.339145960195191, 1.6986542094024006, -7.316982269280614, -7.4089735116666064, -3.0046255099671892, -2.5873212081597377, -6.827621059495563, -1.438531959738429, 1.8796104554474073, 1.5050618611081399, -9.028777963657493, -0.6891704018741098, -6.837056055237005, -5.583166831901322, -0.08426140515610658, -2.8892378920633335, -2.3993629823340865, -6.763798068451533, 3.288598191811139, -8.206104540496137, -4.145173066015854, -4.227512041516999, -10.535386674255394, -8.16948303108025, -5.372696166836505, 0.6429787585704672, -8.122691482350891, -0.30523728485417667, -7.237694943445989, -0.13473236220564644, -5.437492787011896, -2.564590189912019, -5.396626372177929, -7.1683511306506436, 1.1849062433080482, -7.92707764316654, -11.0703241395689, -6.555616270263718, -9.497107742926442, -6.2114905714677455, -7.28886644713213, -6.914132906415123, -6.723028005985412, -6.474677110329841, -2.533929317578626, -7.525411506029455, -1.3099847524292487, -7.554562569783455, -0.9813638358166576, -7.751284491848235, -8.817102676207508, -9.370984076524948, -5.6011046151125345, -2.5060527557251966, -2.3914963973119985, -12.646179375261301, -4.919562103924632, -1.2997636152623437, -5.308285827321867, -2.359816554352985, -2.8208051952601227, -3.12147881303965, -2.5648873878065426, -4.747637220537003, -2.624172953883202, -9.950726813032155, -7.141427173562353, -6.719985768830318, -9.472346941311162, -11.2633340949679, -11.262049026248997, -1.0490965770517695])

random_polyagamma(np.ones(bad_z.shape), bad_z, random_state=rng)
```

### PR DESCRIPTION
**Pull request by zoj613**
closes #83

### CODE REVIEW

**Comment by zoj613** [comment]
@martinjankowiak This PR fixes the issue you were having. I'd appreciate a review of these changes and maybe verifying on your side before I merge. See jupyter output below:

```ipynb
In [1]: import numpy as np
   ...: from polyagamma import random_polyagamma
   ...: 
   ...: bad_state = {'bit_generator': 'PCG64', 'state': {'state': 286445528977372604878304246648472662937,
   ...:              'inc': 87136372517582989555478159403783844777}, 'has_uint32': 1, 'uinteger': 165759272}
   ...: 
   ...: rng = np.random.default_rng(0)
   ...: rng.__setstate__(bad_state) # if this line is commented out the sampler returns as usual
   ...: 
   ...: bad_z = np.array([-7.7159955279217645, -5.688383408336662, ..., -11.262049026248997, -1.0490965770517695])
   ...: 
   ...: random_polyagamma(np.ones(bad_z.shape), bad_z, random_state=rng)
Out[1]: 
array([0.06480045, 0.09556523, 0.03866176, 0.05635552, 0.05808285,
       0.10362004, 0.07145932, 0.06681459, 0.07606001, 0.03960328,
       0.09757399, 0.03384288, 0.08357525, 0.09744253, 0.14979175,
       0.15821123, 0.01561182, 0.1906274 , 0.08124902, 0.06887569,
       0.13828779, 0.12985848, 0.07560077, 0.02174524, 0.0656849 ,
       0.0326521 , 0.06262509, 0.08701867, 0.10914685, 0.08634814,
       0.12132461, 0.07285461, 0.08216356, 0.53011678, 0.04410328,
       0.08960637, 0.03237516, 0.02333878, 0.07034101, 0.12270179,
       0.05114739, 0.02470546, 0.09101826, 0.03753353, 0.43420199,
       0.31547854, 0.07434058, 0.08962173, 0.03122681, 0.06423907,
       0.09992103, 0.03889329, 0.40907573, 0.04972762, 0.08443332,
       0.0331861 , 0.07383895, 0.21156568, 0.02375437, 0.16064011,
       0.15511968, 0.05544921, 0.03468974, 0.09895899, 0.18999056,
       0.15786266, 0.03935569, 0.21828314, 0.2253067 , 0.09377626,
       0.06541529, 0.28789689, 0.10828346, 0.0487434 , 0.12612896,
       0.04882379, 0.24900166, 0.04549486, 0.10802875, 0.06287274,
       0.0783371 , 0.04884058, 0.08697378, 0.04352953, 0.10941918,
       0.08717974, 0.08622359, 0.05203451, 0.04079096, 0.16154658,
       0.03494318, 0.17084883, 0.06094518, 0.09289351, 0.20614002,
       0.43456235, 0.07274774, 0.19438151, 0.04266162, 0.03007659,
       0.08649423, 0.07162172, 0.10535403, 0.01571231, 0.05530639,
       0.27585844, 0.06137601, 0.03899531, 0.07158479, 0.38572719,
       0.1641808 , 0.01632364, 0.03640405, 0.45319565, 0.23438236,
       0.04480479, 0.17741932, 1.18523909, 0.19158178, 0.06913153,
       0.10806838, 0.03637171, 0.06321395, 0.10459718, 0.15511272,
       0.04364698, 0.22063289, 0.04432424, 0.10332783, 0.04631343,
       0.16360763, 0.05938432, 0.24682321, 0.09766731, 0.05088283,
       0.05141575, 0.07719655, 0.04185521, 0.21681528, 0.0276814 ,
       0.12514608, 0.04847786, 0.19478002, 0.04022334, 0.07697026,
       0.02180848, 0.04468513, 0.08002056, 0.06460919, 0.04519808,
       0.12822491, 0.16584231, 0.05484134, 0.04619014, 0.09149664,
       0.25533044, 0.07570376, 0.03042486, 0.11082696, 0.2055575 ,
       0.40679173, 0.05404726, 0.06486755, 0.12171584, 0.10538963,
       0.07476394, 0.0743287 , 0.04321462, 0.02469561, 0.16619639,
       0.08659504, 0.05697804, 0.06997582, 0.04547043, 0.29588109,
       0.04862183, 0.09912302, 0.06120085, 0.07990393, 0.05170703,
       0.01780162, 0.41052266, 0.09317197, 0.22416023, 0.17015127,
       0.03800913, 0.05038368, 0.06819091, 0.06116336, 0.16601597,
       0.03748188, 0.09875945, 0.41730249, 0.13839247, 0.05038348,
       0.03629958, 0.02237369, 0.06737085, 0.05921063, 0.13793648,
       0.52883132, 0.15287834, 0.06239574, 0.05290823, 0.07074641,
       0.0701263 , 0.03216004, 0.09009504, 0.08359783, 0.10717485,
       0.08460443, 0.02409278, 0.12143383, 0.05897423, 0.11761096,
       0.03055956, 0.07017743, 0.02960197, 0.02860937, 0.07035317,
       0.09792273, 0.10065746, 0.08530609, 0.2439539 , 0.08320937,
       0.0577314 , 0.06633372, 0.15290996, 0.04890648, 0.04719016,
       0.06262546, 0.11655502, 0.03733521, 0.03225868, 0.04927151,
       0.03184792, 0.2486868 , 0.04843895, 0.0613028 , 0.20990734,
       0.05536106, 0.15457448, 0.09154746, 0.04728982, 0.02914311,
       0.37280641, 0.05298227, 0.03926289, 0.05993699, 0.25425678,
       0.09065753, 0.0348825 , 0.1364469 , 0.10766854, 0.45706958,
       0.03098665, 0.0229615 , 0.29113927, 0.0718172 , 0.10470633,
       0.09373596, 0.21187842, 0.03916783, 0.06779375, 0.15833019,
       0.09612553, 0.04091125, 0.0593119 , 0.17069756, 0.04657598,
       0.12289571, 0.20407593, 0.07341975, 0.13903534, 0.06797372,
       0.01839591, 0.09225939, 0.21234158, 0.07139172, 0.125778  ,
       0.12381853, 0.1714896 , 0.07110502, 0.13338454, 0.21889546,
       0.11699899, 0.08997228, 0.15104015, 0.05182762, 0.03937113,
       0.18670464, 0.07845328, 0.05809031, 0.02735345, 0.05627254,
       0.04310017, 0.06371783, 0.09527529, 0.03784278, 0.1062358 ,
       0.12074054, 0.07026747, 0.07412658, 0.08999481, 0.10520449,
       0.25125677, 0.05037708, 0.08396454, 0.06115052, 0.04784642,
       0.04661972, 0.0676631 , 0.02300315, 0.03728655, 0.06750432,
       0.1154763 , 0.04593849, 0.03703   , 0.08701148, 0.07552391,
       0.19878586, 0.05271636, 0.19182191, 0.03011243, 0.17898338,
       0.10943263, 0.15688014, 0.0680296 , 0.08768696, 0.10552324,
       0.40117018, 0.04483716, 0.10158448, 0.0418921 , 0.22325162,
       0.20211339, 0.16484312, 0.18732399, 0.18330451, 0.04828012,
       0.09848161, 0.08120127, 0.1279053 , 0.04405975, 0.04106071,
       0.02620072, 0.026083  , 0.0464953 ])
```

**Comment by martinjankowiak** [comment]
@zoj613 thanks for the quick response! i'm not really sure how i can check this for you. if i clone this repo and checkout this branch will the C get compiled as needed? not really sure how that sort of thing works...

**Comment by zoj613** [comment]
If you have poetry installed in your environment, then you can checkout this branch and then run `poetry install`  to install the Dev dependencies followed by `make install` to build and install the python library. Assuming that the repo directory is in your $PYTHONPATH then just a python REPL and test it using your original code.

**Comment by martinjankowiak** [comment]
great, thanks for the instructions. yup i can confirm that this PR eliminates the issue in the repro script 👍 

unfortunately i can't speak to the specific numerical changes, as i've never taken the time to look into the details of PG sampling strategies

**Comment by zoj613** [comment]
Thats good to hear. I am fairly confident that the source of the hang was the line changed here after doing some debugging on the C-side. The changes themselves involve an algebraic re-arrangement of the argument to the sqrt function so as to avoid taking the difference of two terms and instead use addition that guarantees positive sign. I explained the math in the last sentence of my comment in the corresponding issue.

File: src/pgm_devroye.c [hunk 1]
```diff
@@ -129,8 +132,9 @@ random_right_bounded_invgauss(bitgen_t* bitgen_state, parameter_t* const pr)
     }
     do {
         double y = random_standard_normal(bitgen_state);
-        double w = (pr->z + 0.5 * y * y) / pr->z2;
-        x = w - sqrt(w * w - 1 / pr->z2);
+        double y_z2 = y * y / pr->z2;  /* (y/z)^2 */
+        double w = 1. / pr->z + 0.5 * y_z2;
+        x = w - sqrt(y_z2 * (1. / pr->z + 0.25 * y_z2));  /* See GH-issue #83 */
```
Comment (martinjankowiak) [inline src/pgm_devroye.c:137]: i don't understand what's going on above with the `else if` but this part makes sense to me. i can confirm the algebra. would it make sense to ensure that `x` is non-negative with something like `x=max(0, x)`?

Comment (zoj613) [reply src/pgm_devroye.c]: You're right, I could have just went with that instead of rewriting the whole expression.I updated it in [`94233c4` (#85)](https://github.com/zoj613/polyagamma/pull/85/commits/94233c4f650cb743a47fb2a228130185635c5457)

**Comment by zoj613** [comment]
thanks @martinjankowiak for the review and issue report!
